### PR TITLE
added swagger client and updated resources to expand link arrays and …

### PR DESCRIPTION
**Pull request by howarddierking**
added Swagger client to read only API in order to see what value a swagger library adds for consuming the API from the browser. 

The big discovery here is that because Swagger reduces the API to a set of functions, it is really anathema to using links, not only for state transitions, but also for identifying resources. This is because Swagger clients expect to build the resource identifier (URL) from the tokens supplied in the Swagger definition. This means that for a client to take advantage of a Swagger library (dynamic or generated), it needs to pass the _entity_ identifier in responses so that the client can make progress. Because of this finding, I needed to make modifications to the JSON documents to include surrogate IDs (which were previously embedded in the _resource_ identifier - the URL)

### CODE REVIEW

**Comment by howarddierking** [comment]
Note that rather than modify the original resources (and thereby break the existing JSON client), I've created an additional client and also created new resource documents (`*.swfr.json` - stands for "Swagger-friendly")

**Comment by howarddierking** [comment]
Stepping back for a sec, I think that perhaps approaches like that of Swagger diverge from the RESTful style in 2 ways:
- emphasis on entities over resources
- emphasis on functions over state transitions

**Comment by howarddierking** [comment]
Also had an [insightful conversation on Twitter](https://twitter.com/SleepyDaddySoft/status/749364022701469696) with someone who had found generated swagger clients to be useful in conjunction with TypeScript. Though I haven't verified, I suspect that there's a stronger allure in strongly typed environments, in part at least because of added support from IDEs.

Still, I remember the sins I helped commit with WCF - and that's a little too fresh in my memory to buy that argument.

**Comment by dorongrinstein** [comment]
I find that adopting Swagger helps on the server side, even more so than generated clients. It keeps your service implementation "honest" so you can't really return something unexpected because if you use the right tooling on the server-side, the server will throw an error when you return incorrect stuff. For example: if an error condition is defined as {"message": "some string"}, you can't return {"status": 400} because you get sloppy in some code path.

This strong-typing of expected inputs and outputs makes the server more resilient (by strictly adhering to the contract). This is in addition to making the Swagger UI help the designer reason about the service interface, and the service consumer having a concise documentation that is testable right in the UI. Is it perfect? like most things, no. But it is good when you get the development workflow going. I found an article that helped me get a development workflow that is very pleasant. Take a look at https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger 

The article touches on using the swagger CLI which has things like mocks which I highly recommend. It truly makes RESTful service development quicker and more pleasant.

**Comment by howarddierking** [comment]
I'll check out that workflow, @dorongrinstein. However, one point that I really don't want to get lost in the practicalities of tooling. 

_A Swagger-designed API is at its core not RESTful_ 

As I've mentioned above, the goals of Swagger, while not fundamentally wrong and possibly even better for some circumstances, are counter to the constraints that REST would impose on the interactions between the client and server.

**Comment by dorongrinstein** [comment]
Yes, practicality is way overrated. Abstract ideas and theories built the statue of liberty, not hands and tools ;) I understand where you're coming from and obviously the velocity of tools and their churn is incredible. I gave the specific tooling example to make it concrete and Swagger itself is a tool and it too will be replaced by something shinier, sooner or later. 

Please give a concrete example of what makes a Swagger-designed API not RESTful. Not in a corner case that you can find but in something obvious. You could argue that a 747 is not an airplane because under the right conditions it does not generate lift, but last I checked, it flies.

**Comment by howarddierking** [comment]
See above remarks. Swagger is not RESTful because it goes against using links. In practice, it also violates the uniform interface constraint in that it emphasizes entities over resources. A practical example is the one I mentioned - resource identifiers (URLs are meaningless in a swagger implementation)

**Comment by dorongrinstein** [comment]
I see. we can extend Swagger. It is open source.

**Comment by howarddierking** [comment]
I don't think you can extend it in that direction without making it into something fundamentally different than intended. In fact, I think that doing what you're alluding to would turn it into hydra

**Comment by dorongrinstein** [comment]
Here is a definition from a Swagger file I created for a group management service:

Group:
    required:
      - id
      - name

```
properties:
  id:
    description: uuid representing the unique group ID
    type: string
  name:
    description: the name of the group. multiple groups can have the same name, depending of their position in the hierarchy
    type: string
  pathString:
    description: a slash delimited string representing the hierarchical position of a given group
    type: string

  path:
    description: an array of path ids, internal representation of the group path information
    type: array
    items:
      type: string

  members:
    description: a URL to the array of group members
    type: string
```

Notice that the members property is meant to be a URL (resource) that points to the members assigned to the group. Is this not sufficient?

**Comment by howarddierking** [comment]
I'll test later, but no, I don't think so - you're still relying on your client to build urls with parameters. 

It's still philosophically WSDL - still RPC

**Comment by dorongrinstein** [comment]
no, it is the server who returns the URL, it could return an array of [name, description, url] and let the client simply render it. So the URLs are provided by they server.

**Comment by howarddierking** [comment]
Not true - the base url and all endpoint paths are provided by the swagger definition. So the client still has. To buil up the strings.

**Comment by dorongrinstein** [comment]
Are you thinking about a client that knows nothing about the server expected output? In such a case, I suppose you could specify that the output type of certain fields are HTML (base64 encoded, or otherwise) and then the server could totally be in control of what gets rendered on the client and there is nothing in Swagger that prevents that. Unless I don't understand the problem domain and we need to have a conversation so you can explain.

**Comment by howarddierking** [comment]
I think at this point we need to shift to in person 😀

But the questions/comments that you're raising are core to why IMO most people miss what REST is actually describing

**Comment by howarddierking** [comment]
Again, not saying Swagger is bad, just that it ain't REST

**Comment by dorongrinstein** [comment]
let me know when you're available and let's chat..

**Pull request merged**
